// templates/electron-vue/src/components/HelloWorld.vue
<script setup lang="ts">
import os from 'node:os';
import { ref } from 'vue';

defineProps<{ msg: string }>();

const count = ref(0);

const versions = ['chrome', 'node', 'electron']
  .map(s => `${s}: ${process.versions[s]}`)
  .concat([`platform: ${os.platform()} ${os.arch()}`]);
</script>

<template>
  <h1>{{ msg }}</h1>

  <div class="card">
    <div style="margin-bottom: 1em">
      {{ versions.join(', ') }}
    </div>
    <button type="button" @click="count++">
      count is {{ count }}
    </button>
    <p>
      Edit
      <code>components/HelloWorld.vue</code> to test HMR
    </p>
  </div>

  <p>
    Check out
    <a href="https://vuejs.org/guide/quick-start.html#local" target="_blank">create-vue</a>, the
    official Vue + Vite starter
  </p>
  <p>
    Install
    <a href="https://github.com/vuejs/language-tools" target="_blank">Volar</a>
    in your IDE for a better DX
  </p>
  <p class="read-the-docs">
    Click on the Vite and Vue logos to learn more
  </p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>

// templates/crx-react/src/components/HelloWorld.tsx
import { useState } from 'react';

export default function HelloWorld(props: { msg: string }) {
  const [count, setCount] = useState(0);

  return (
    <>
      <h1>{props.msg}</h1>

      <div className="card">
        <button type="button" onClick={() => setCount(count + 1)}>
          count is
          {' '}
          {count}
        </button>
        <p>
          Edit
          <code>src/components/HelloWorld.tsx</code>
          {' '}
          to test HMR
        </p>
      </div>

      <p>
        Check out
        <a href="https://github.com/crxjs/create-crxjs" target="_blank" rel="noreferrer">create-crxjs</a>
        , the official starter
      </p>

      <p className="read-the-docs">
        Click on the Vite, React and CRXJS logos to learn more
      </p>
    </>
  );
}
